### ISSUE TITLE
Add acknowledgement of CCG funding

### ISSUE THREAD

**Issue by willu47** [SGIModel/MUSE-Dashboard#3]
"This research received funding from the FCDO Climate Compatible Growth Project” and, if applicable, “This research was co-funded by NAME OF FUNDER, if applicable grant number XXX” and, if applicable “contributions in kind were made by org-XXX <if applicable> by individual(s)-XXX

**Comment by alexanderkell** [comment]
Have added an acknowledgement in [README.md](https://github.com/SGIModel/MUSE-Dashboard/blob/main/README.md). No co-funders for this project.
